services:
  - type: web
    name: construction-project
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn construction_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
